### PR TITLE
User can login

### LINKED ISSUE #7: Authentication: User - Login
- User can login with there email and password
- sanitize the input using the expected characters
- Check if email and password is correct 
- Success

### PR DESCRIPTION
**Pull request by spykelionel**
: with their email and password
: check if the email and password are correct
- Fixes #7

### CODE REVIEW

**Comment by codewithmide** [comment]
> : with their email and password : check if the email and password are correct
> 
> * Fixes [Authentication: User - Login #7](https://github.com/Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022/issues/7)

@spykelionel thank you for the contribution. I was reading through your codebase and I found something there.
Kindly confirm if this is a typo error or it's just a function on it's own. 
confirmation

**Comment by spykelionel** [comment]
It's not a typo. It's a function. Thanks @codewithmide

**Review by codewithmide — DISMISSED** [review]
LGTM 🚀

**Comment by ingressive4good** [comment]
kindly fix your merge conflict

**Comment by spykelionel** [comment]
> kindly fix your merge conflict

Alright. Done

**Pull request merged**
