### PR TITLE
[hacktoberfest:] feat: Implement get products enpoint

### PR DESCRIPTION
**Pull request by Ayo-Awe**
This PR implements the get products endpoint #58

### CODE REVIEW

**Comment by Timmy-id** [comment]
Make sure you pull the current develop branch before working on your feature.

**Comment by Ayo-Awe** [comment]
Resolved @Timmy-id

**Comment by ingressive4good** [comment]
You have conflicts please resolve

**Comment by Ayo-Awe** [comment]
@ingressive4good fixed

**Review by Timmy-id — APPROVED** [review]
It looks fine now.

**Comment by Timmy-id** [comment]
@ingressive4good
The pull request works fine. It can be merged.

**Pull request merged**
