### PR TITLE
Update single product endpoint

### LINKED ISSUE #62: Update product by Id
## Title
Update Single product

## Summary

To update a single product

## Environment

browser

## Steps to reproduce

create an update product service, controller and endpoint

## Expected result

A product should be able to be updated

## Current result

Not implemented

## Possible Fix

new

## Additional information

none

## Example

none
 Fixes part of #51

### PR DESCRIPTION
**Pull request by spykelionel**
fixes #62

### CODE REVIEW

**Review by Timmy-id — CHANGES_REQUESTED** [review]
Check the hasImages middleware you created, it's giving errors.
The req.body.images is not declared as an array, so it's giving errors. Check that also.
Also, make sure you validate all the required fields.

**Comment by ingressive4good** [comment]
@Timmy-id should i merge this?

**Review by Timmy-id — CHANGES_REQUESTED** [review]
This is the error I'm getting: "message": "Cannot read properties of undefined (reading 'length')"
Since the images field is an array in the database, you have to declare the images field has an array.
Also check the conflicting files.
I'll send something to your telegram now. Compare what you have with that.

**Review by Timmy-id — APPROVED** [review]
I works fine now.

**Pull request merged**
