### PR TITLE
User product

### LINKED ISSUE #9: User: Product
- Users should be able to create products on their dashboard.
- Each product should have a reference id of the user who created it.
- Each product should also have a reference to whoever is interested in it.
- Product should have a category.
- Users should be able to delete a product.
- Users should be able to see who is interested in their product.

### PR DESCRIPTION
**Pull request by spykelionel**
All, fixes #9

### CODE REVIEW

**Comment by codewithmide** [comment]
@spykelionel Thank you for the contribution. Please note that you have drafted the PR. I'll like to confirm if it is still a work in progress.

**Comment by spykelionel** [comment]
It's still work in progress. Thanks @codewithmide

**Comment by ingressive4good** [comment]
Kindly fix your merge conflicts

**Comment by ingressive4good** [comment]
fix your merge conflict

**Comment by spykelionel** [comment]
> fix your merge conflict

Alright! Done. Thanks @ingressive4good

**Comment by codewithmide** [comment]
> src/modules/user.controller.js

the above file still has conflict issues.

**Comment by spykelionel** [comment]
> > src/modules/user.controller.js
> 
> the above file still has conflict issues.

Fixed

**Review by codewithmide — APPROVED** [review]
well done chief!🚀

**Pull request merged**
